// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserOrgs.Data;

#nullable disable

namespace UserOrgs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserOrgs.Data.Organisation", b =>
                {
                    b.Property<string>("orgId")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("orgId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("UserOrgs.Data.User", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("passwordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .HasColumnType("text");

                    b.HasKey("userId");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserOrgs.Data.UserOrganisation", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("text");

                    b.Property<string>("organisationId")
                        .HasColumnType("text");

                    b.HasKey("userId", "organisationId");

                    b.HasIndex("organisationId");

                    b.ToTable("UserOrganisations");
                });

            modelBuilder.Entity("UserOrgs.Data.UserOrganisation", b =>
                {
                    b.HasOne("UserOrgs.Data.Organisation", "organisation")
                        .WithMany("userOrganisations")
                        .HasForeignKey("organisationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UserOrgs.Data.User", "user")
                        .WithMany("userOrganisations")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("organisation");

                    b.Navigation("user");
                });

            modelBuilder.Entity("UserOrgs.Data.Organisation", b =>
                {
                    b.Navigation("userOrganisations");
                });

            modelBuilder.Entity("UserOrgs.Data.User", b =>
                {
                    b.Navigation("userOrganisations");
                });
#pragma warning restore 612, 618
        }
    }
}
